name: Tests, linter, mypy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build test container
      run: docker build -t tempoggl .

    - name: Run all checks
      run: docker run tempoggl
